# Generated by Django 2.2.16 on 2022-07-05 05:18

import django.db.models.deletion
from django.db import migrations, models

import posts.validators


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20220616_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='group',
            field=models.ForeignKey(blank=True, help_text='Группа, к которой будет относиться пост', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='posts.Group', verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(help_text='Введите текст поста', validators=[posts.validators.validate_not_empty], verbose_name='Текст поста'),
        ),
    ]
